apiVersion: v1
kind: Service
metadata:
  name: grcp-service
  namespace: so1-p2
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: grcp-port
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grcp-port2
  selector:
    app: grcp-app
  type: NodePort