apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: so1-p2
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: node-port
  selector:
    app: node-app
  type: LoadBalancer