apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node
  namespace: so1-p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
