apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis
  namespace: so1-p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-db
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50