apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: so1-p2
  labels:
    app: node-app
spec:
  replicas:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-server
        image: rodrialeh01/apinodejsp2:3.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "300m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: REDIS_PORT
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_PASSWORD
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_NAME
        