apiVersion: apps/v1
kind: Deployment
metadata:
  name: grcp-deployment
  namespace: so1-p2
  labels:
    app: grcp-app
spec:
  replicas:
  selector:
    matchLabels:
      app: grcp-app
  template:
    metadata:
      labels:
        app: grcp-app
    spec:
      containers:
      - name: grcp-client
        image: rodrialeh01/clientgrcpp2:2.0.0
        ports:
        - containerPort: 4000
      - name: grcp-server
        image: rodrialeh01/servergrcpp2:2.0.0
        ports:
        - containerPort: 3000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_PASSWORD
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mi-secret-so1p2
                key: SQL_NAME
