version: '3'

services:
  backend:
    image: 'rodrialeh01/agente-backed'
    container_name: 'agente-backend'
    privileged: true
    volumes:
      - type: bind
        source: /proc
        target: /proc
    pid: host
    ports:
      - '3000:3000'

