apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-so1p2
  namespace: so1-p2
type: Opaque
data:
  SQL_USER: cm9vdA==
  SQL_PASSWORD: c28xcDIyMDE5MDAwNDI=
  SQL_HOST: MzUuMjMxLjEyMi4xMzg=
  SQL_PORT: MzMwNg==
  SQL_NAME: c2lzdGVtYW5vdGFz
  REDIS_PORT: NjM3OQ==
  REDIS_HOST: cmVkaXMtc2VydmljZQ==